### ISSUE TITLE
jsqueeze fails to minimize ExtJS

### ISSUE THREAD

**Issue by felicitus** [tchwork/jsqueeze#34] opened 2016-01-02 23:37 UTC
When I attempt to minify ExtJS, I receive the following invalid code:

```
Ext.Date=(function(){var e,t=Date,r=/(\\.)/g,l=/([gGhHisucUOPZ]|MS)/,d=/([djzmnYycU]|MS)/,s=/\\/gi,u=/\{(\d+)\}/g,o=new RegExp('\\/Date\\(([-+])?(\\d+)(?:[+-]\\d{4})?\\)\\/'),i=Ext.String.leftPad,a=['var me = this, dt, y, m, d, h, i, s, ms, o, O, z, zz, u, v, W, year, jan4, week1monday, daysInMonth, dayMatched,','def = me.defaults,','from = Ext.Number.from,','results = String(input).match(me.parseRegexes[{0}]);','if(results){','{1}','if(u != null){','v = new Date(u * 1000);','}
```

Firefox says: `SyntaxError: unterminated string literal` in colum 480.

**Comment by nicolas-grekas** [comment] 2016-01-04 09:11
I just tried reproducing this bug without success so far. Can you link to the original source you're squeezing? Can you try also with latest master?

**Comment by felicitus** [comment] 2016-01-04 10:44
I tried to minimize the file https://github.com/partkeepr/extjs6/blob/master/build/ext-all-debug.js

I will try with dev-master later.

**Comment by nicolas-grekas** [comment] 2016-01-04 11:01
Thanks for the link, I can reproduce the issue now

**Comment by nicolas-grekas** [comment] 2016-01-04 11:34
After some investigation #34 and #30 share the same root cause, and are related to #15.

**Comment by nicolas-grekas** [comment] 2016-01-04 14:19
Should be fixed in master, can you please confirm?

**Comment by felicitus** [comment] 2016-01-04 15:43
Yes, I can confirm that the issue is fixed. Thank you!

**Comment by nicolas-grekas** [comment] 2016-01-04 15:46
Cool

**Closed by nicolas-grekas** 2016-01-04 15:46 UTC
