### ISSUE TITLE
Static strings get totally mangled

### ISSUE THREAD

**Issue by nickturner** [tchwork/jsqueeze#30] opened 2015-10-12 02:50 UTC
Constant strings get altered by the squeezer which isn't very desirable as these are not code to be squashed.

For example the script;

var str = 'I hope you do not wish this to correctly return !' + '}else you may get upset';

when squeezed the space will be removed from between the 'return' and the '!' and a new line added between the  '}' and the 'else'. The new line being inserted into the string constant then causes the compiler to fail due to an un-terminated string.

**Comment by nicolas-grekas** [comment] 2016-01-04 10:37
If I parse only your expression (`var str = 'I hope you do not wish this to correctly return !' + '}else you may get upset';`),
I get `var str='I hope you do not wish this to correctly return !}else you may get upset';` which looks correct to me.
Same for you?
Which would mean that the bug is related to some code before this one.
Can you reproduce with latest master?
If yes, can you please post a full code excerpt that triggers the buggy behavior?

**Comment by nicolas-grekas** [comment] 2016-01-04 11:34
Closing as duplicate of #34 where I have a reproducer

**Closed by nicolas-grekas** 2016-01-04 11:34 UTC

**Comment by nicolas-grekas** [comment] 2016-01-04 14:19
Should be fixed in master, can you please confirm?
